<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-01-23T12:53:18 IST" name="Default suite" finished-at="2023-01-23T12:53:29 IST" duration-ms="10129">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.tutorialninja.utomation.runner.TestNGRunner@d86a6f]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2023-01-23T12:53:18 IST" name="Default test" finished-at="2023-01-23T12:53:29 IST" duration-ms="10129">
      <class name="com.tutorialninja.utomation.runner.TestNGRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:com.tutorialninja.utomation.runner.TestNGRunner@d86a6f]" started-at="2023-01-23T12:53:19 IST" name="setUpClass" finished-at="2023-01-23T12:53:20 IST" duration-ms="1646" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@7237f3c1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:com.tutorialninja.utomation.runner.TestNGRunner@d86a6f]" started-at="2023-01-23T12:53:20 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2023-01-23T12:53:29 IST" duration-ms="8316" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify Whether the User is not able to login with invalid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login functionality scenarios"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Warning: No match for E-Mail Address and/or Password..] but found [Warning: No match for E-Mail Address and/or Password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Warning: No match for E-Mail Address and/or Password..] but found [Warning: No match for E-Mail Address and/or Password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.tutorialninja.stepdef.Login.i_should_see_that_the_credentials_are_invalid(Login.java:44)
at âœ½.I should see that the credentials are invalid(file:///C:/Users/sh614/eclipse-workspace/com.tutorialninja/src/test/java/features/Login.feature:15)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:com.tutorialninja.utomation.runner.TestNGRunner@d86a6f]" started-at="2023-01-23T12:53:29 IST" name="tearDownClass" finished-at="2023-01-23T12:53:29 IST" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.tutorialninja.utomation.runner.TestNGRunner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
